FROM ubuntu

RUN apt-get update && apt-get install -y mmv && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

COPY --chmod=777 run-frontend-tests.sh /frontend/

# running frontend tests
WORKDIR /frontend
RUN ./run-frontend-tests.sh 2>&1 | tee jest.log && echo "${PIPESTATUS[0]}" > jest.exit-code
COPY jest-results.xml jest.xml

VOLUME /reports

CMD cp jest.* /reports/
