# docker-compose.yml file

services:

  cucumber:
    image: busybox
    command: /bin/sh -c 'cp -r /mock-reports/* /reports && echo "this will take some time..." && sleep 5m'
    volumes:
      - ./mock-reports:/mock-reports:ro
      - ./results/cucumber:/reports

  bouncer:
    image: busybox
    command: /bin/sh -c 'sleep 1m && echo "Who of you folks wound the clock? It is really time to stop!" && echo "aborting cucumber run after 1m"'

volumes: {}
configs: {}
secrets: {}
