# docker-compose.yml file

services:

  cucumber:
    image: busybox
    command: /bin/sh -c 'cp -r /mock-reports/* /reports && echo "this will take some time..." && sleep 300'
    volumes:
      - ./mock-reports:/mock-reports:ro
      - ./results/cucumber:/reports

volumes: {}
configs: {}
secrets: {}
