name: pipeline
on: [push]
jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'initializing...'

  java:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'compiling...'

  backend:
    needs: [init, java]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'building...'
          echo '::warning::this is a warning'

  test-java:
    name: test (java)
    runs-on: ubuntu-latest
    needs: [init, java]
    steps:
      - uses: actions/checkout@v3
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: metasfresh
      - name: run-tests
        run: |
          docker buildx build -t tests .
      - name: publish results
        run: |
          docker run --rm -v "$(pwd)/junit:/reports" tests          
          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;
          testspace "[junit/foo]junit/foo/junit.log{$(cat junit/foo/junit.exit-code):foo junit tests}"          
          testspace "[junit/bar]junit/bar/junit.log{$(cat junit/bar/junit.exit-code):bar junit tests}"
      - name: assert success
        run: |
          shopt -s globstar
          exit $(awk '{ sum += $1 } END { print sum }' junit/**/junit.exit-code)
  frontend:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'building...'

  test-frontend:
    name: test (frontend)
    runs-on: ubuntu-latest
    needs: [init, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'testing...'
          echo '::error::frontend test failure'

  test-integration:
    name: test (integration)
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'integration testing...'
          echo '::error::integration test failure'

  redeploy:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    steps:
      - name: do-it
        run: |
          echo 'dispatching deployment...'
          echo '::notice::this is a notice'