name: pipeline
on: [push]
jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'initializing...'

  java:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'compiling...'

  backend:
    needs: [init, java]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'building...'

  test-java:
    name: test (java)
    runs-on: ubuntu-latest
    needs: [init, java]
    steps:
      - uses: actions/checkout@v3
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: metasfresh
      - name: run-tests
        run: |
          docker buildx build -f Dockerfile.junit -t tests .
      - name: publish results
        run: |
          docker run --rm -v "$(pwd)/junit:/reports" tests                                                # extracting test results from docker image
          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;                                     # upload all junit xml's to testspace 
          testspace "[junit/foo]junit/foo/junit.log{$(cat junit/foo/junit.exit-code):foo junit tests}"    # upload foo log with exit code 
          testspace "[junit/bar]junit/bar/junit.log{$(cat junit/bar/junit.exit-code):bar junit tests}"    # upload bar log with exit code
          testspace "[junit/baz]junit/baz/junit.log{$(cat junit/baz/junit.exit-code):baz junit tests}"    # upload baz log with exit code
      - name: assert success
        run: |
          if [ $(cat junit/foo/junit.exit-code) != 0 ]; then cat junit/foo/junit.log && exit 1; fi        # print foo log and exit if foo failed
          if [ $(cat junit/bar/junit.exit-code) != 0 ]; then cat junit/bar/junit.log && exit 1; fi        # print bar log and exit if foo failed
          if [ $(cat junit/baz/junit.exit-code) != 0 ]; then cat junit/baz/junit.log && exit 1; fi        # print baz log and exit if foo failed
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: junit-logs
          path: junit/**/junit.log

  frontend:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
          echo 'building...'

  test-frontend:
    name: test (frontend)
    runs-on: ubuntu-latest
    needs: [init, frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: metasfresh
      - name: run-tests
        run: |
          docker buildx build -f Dockerfile.jest -t tests .
      - name: publish results
        run: |
          docker run --rm -v "$(pwd)/jest:/reports" tests                                                 # extracting test results from docker image
          testspace "[jest/frontend]jest/jest.xml"                                                        # upload junit xml to testspace 
          testspace "[jest/frontend]jest/jest.log{$(cat jest/jest.exit-code):frontend junit tests}"       # upload test log with exit code
      - name: assert success
        run: |
          if [ $(cat jest/jest.exit-code) != 0 ]; then cat jest/jest.log && exit 1; fi                    # print frontend log and exit if frontend failed
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: jest-logs
          path: jest/jest.log

  test-integration:
    name: test (integration)
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'integration testing...'

  redeploy:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    steps:
      - name: do-it
        run: |
          echo 'dispatching deployment...'