name: pipeline
on: [push]
jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'initializing...'

  java:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'compiling...'

  backend:
    needs: [init, java]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'building...'

  test-java:
    runs-on: ubuntu-latest
    needs: [init, java]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'testing...'
          
  frontend:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'building...'

  test-frontend:
    runs-on: ubuntu-latest
    needs: [init, frontend]
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'testing...'

  test-integration:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: do-it
        run: |
          echo 'integration testing...'

  redeploy:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    steps:
      - name: do-it
        run: |
          echo 'dispatching deployment...'
